### ISSUE TITLE
Duot - How it Works?

### ISSUE THREAD

**Issue by alqmte** [alqmte/duot-governance#1]
### Phase 1: Backlog; Drafting and Analysis

- Issues are created in the backlog during the analysis phase.

#### Actions
  * Client:
    - [ ] Create a requirement ticket here, a bug report, question, etc.
    - [ ] Collaborate with the PM on a budget and priority for new requirements.
    - [ ] Write Acceptance Criteria

  * Developers & Testers:
    - [ ] Assign yourself an issue from here not necessarily meaning that you'll work on the task but `If` 
      - [ ] You are sure you understand the requirements.
      - [ ] You're willing to take this task from the queue within the set milestone if you're free, if not then
      - [ ] You think that the budget for the task is convenient, and you vote for the validity of the issue cost.

#### Guidelines
 - Client is responsible for verifying that the issue description is clear, and all acceptance criteria is written before moving to the Queue.
- Developers and Testers are rewarded for verifying 

=======================================================

### Phase 2: Queue; On Board

- Issues here are sorted out in priority by client, and have developers and testers assigned and ready to work on it once they are available.

#### Actions

 - Developers can  move issues from Queue to In-Progress issues here only once at a time.

#### Guidelines

- No participant can take two tasks from the queue, once participant is free, they can come pop an item from the queue and move it to in-progress.

==========================================================

### Phase 3: In-Progress

- Items here are in progress of development,

#### Actions
* Developers once they are done,
  - Code is pushed to the developer machine github_username.prohealth.io
  - Pull request is issued.

#### Guidelines

* Developers should be working on one item at a time.

==========================================================

### Phase 4: Staging

- All Items here are supposed to be 
  [ ] Code is Merged with the latest master code on time of submission.
  [ ] Deployed to developer machine at developer_github_username.prohealth.io
  [ ] Passing acceptance criteria written in the issue.

#### Actions
 - Items are moved from here to Prohealth.mobi if branch is accepted.
- Items move Back into in-progress, and developer is ought to stop working on any other issue until bugs are resolved.

#### Guidelines
- Earlier submitter are reviewed first. meaning that in case someone else claimed the branch before you, you're ought to merge your code to his code after his code is merged.
- If your branch is accepted, developers are rewarded a successful merge token, and their point rate is increased by a fixed percent (agreed in contract) with each submission.
  - Their code is merged and deployed to beta server
- If your branch had an issue, regarding a functionality that is clearly stated in the issue description, with each failed submission your point rate is decreased by the same percent.

====================================
- Anyone can post a proposal.
- Either a change to the policy, a pull or merge request to our policy
- Leave a comment with votes +1 or -1 on existing proposals.
- Your most +1 or -1 will be the only one considered.

Pros:
- Eliminates time stamping problem. ( conflict of two people voting at the same time)

**Comment by alqmte** [comment]
Validate no of votes authenticity by
1- looking through git api of issue change history
2- detecting spammers or cheaters by neglicting their changes.
3- Method return total no of real value

**Comment by alqmte** [comment]
I believe it's easier to leave a comment with just the +1 comment.
We will always take your most recent comment either it's a +1, or a -1, so you can change your vote anytime.
